export const categoryConstants = {
    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_FALIURE: 'CREATE_CATEGORY_FALIURE',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS'
};