export const categoryConstants = {
    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_FALIURE: 'CREATE_CATEGORY_FALIURE',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    FETCH_CATEGORY_REQUEST: 'FETCH_CATEGORY_REQUEST',
    FETCH_CATEGORY_FALIURE: 'FETCH_CATEGORY_FALIURE',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    CHANGE_STATUS_REQUEST: 'CHANGE_STATUS_REQUEST',
    CHANGE_STATUS_FALIURE: 'CHANGE_STATUS_FALIURE',
    CHANGE_STATUS_SUCCESS: 'CHANGE_STATUS_SUCCESS',
    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_FALIURE: 'DELETE_CATEGORY_FALIURE',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS'
};

export const productConstants = {
    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_FALIURE: 'CREATE_PRODUCT_FALIURE',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    FETCH_PRODUCT_REQUEST: 'FETCH_PRODUCT_REQUEST',
    FETCH_PRODUCT_FALIURE: 'FETCH_PRODUCT_FALIURE',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_CAT_REQUEST: 'FETCH_PRODUCT_CAT_REQUEST',
    FETCH_PRODUCT_CAT_FALIURE: 'FETCH_PRODUCT_CAT_FALIURE',
    FETCH_PRODUCT_CAT_SUCCESS: 'FETCH_PRODUCT_CAT_SUCCESS',
    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_FALIURE: 'DELETE_PRODUCT_FALIURE',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_FALIURE: 'UPDATE_PRODUCT_FALIURE',
    UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
    TOPUP_PRODUCT_REQUEST: 'TOPUP_PRODUCT_REQUEST',
    TOPUP_PRODUCT_FALIURE: 'TOPUP_PRODUCT_FALIURE',
    TOPUP_PRODUCT_SUCCESS: 'TOPUP_PRODUCT_SUCCESS',
    NOTIFICATION_PRODUCT_REQUEST: 'NOTIFICATION_PRODUCT_REQUEST',
    NOTIFICATION_PRODUCT_FALIURE: 'NOTIFICATION_PRODUCT_FALIURE',
    NOTIFICATION_PRODUCT_SUCCESS: 'NOTIFICATION_PRODUCT_SUCCESS',
};
export const vendorConstants = {
    CREATE_VENDOR_REQUEST: 'CREATE_VENDOR_REQUEST',
    CREATE_VENDOR_FALIURE: 'CREATE_VENDOR_FALIURE',
    CREATE_VENDOR_SUCCESS: 'CREATE_VENDOR_SUCCESS',
    FETCH_VENDOR_REQUEST: 'FETCH_VENDOR_REQUEST',
    FETCH_VENDOR_FALIURE: 'FETCH_VENDOR_FALIURE',
    FETCH_VENDOR_SUCCESS: 'FETCH_VENDOR_SUCCESS',
    DELETE_VENDOR_REQUEST: 'DELETE_VENDOR_REQUEST',
    DELETE_VENDOR_FALIURE: 'DELETE_VENDOR_FALIURE',
    DELETE_VENDOR_SUCCESS: 'DELETE_VENDOR_SUCCESS'
};

export const clientConstants = {
    FETCH_PENDING_REQUEST: 'FETCH_PENDING_REQUEST',
    FETCH_PENDING_FALIURE: 'FETCH_PENDING_FALIURE',
    FETCH_PENDING_SUCCESS: 'FETCH_PENDING_SUCCESS',
    FETCH_DEACTIVATE_REQUEST: 'FETCH_DEACTIVATE_REQUEST',
    FETCH_DEACTIVATE_FALIURE: 'FETCH_DEACTIVATE_FALIURE',
    FETCH_DEACTIVATE_SUCCESS: 'FETCH_DEACTIVATE_SUCCESS',
    DEACTIVATE_REQUEST: 'DEACTIVATE_REQUEST',
    DEACTIVATE_FALIURE: 'DEACTIVATE_FALIURE',
    DEACTIVATE_SUCCESS: 'DEACTIVATE_SUCCESS',
    ACTIVATE_REQUEST: 'ACTIVATE_REQUEST',
    ACTIVATE_FALIURE: 'ACTIVATE_FALIURE',
    ACTIVATE_SUCCESS: 'ACTIVATE_SUCCESS',
};

export const orderConstants = {
    FETCH_ORDERS_REQUEST: 'FETCH_ORDERS_REQUEST',
    FETCH_ORDERS_FALIURE: 'FETCH_ORDERS_FALIURE',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORD_ID_REQUEST: 'FETCH_ORD_ID_REQUEST',
    FETCH_ORD_ID_FALIURE: 'FETCH_ORD_ID_FALIURE',
    FETCH_ORD_ID_SUCCESS: 'FETCH_ORD_ID_SUCCESS',
};