export const categoryConstants = {
    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_FALIURE: 'CREATE_CATEGORY_FALIURE',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    FETCH_CATEGORY_REQUEST: 'FETCH_CATEGORY_REQUEST',
    FETCH_CATEGORY_FALIURE: 'FETCH_CATEGORY_FALIURE',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS'
};

export const productConstants = {
    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_FALIURE: 'CREATE_PRODUCT_FALIURE',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    FETCH_PRODUCT_REQUEST: 'FETCH_PRODUCT_REQUEST',
    FETCH_PRODUCT_FALIURE: 'FETCH_PRODUCT_FALIURE',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS'
};